/* *************** USER *************** */
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

/* *************** ALL EMPLOYEES *************** */
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';
export const FETCH_EMPLOYEES_LOADING = 'FETCH_EMPLOYEES_LOADING';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';